sudo: required
services:
  - docker

before_install:
  - docker build -t harrychang/docker-aws-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harrychang/docker-aws-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app:  "docker-aws-react"
  env: "DockerAwsReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-725427206909"
  bucket_path: "docker-aws-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY